<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2018 LibreWorks contributors
 * @license   Apache-2.0
 */
namespace Caridea\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-18 at 14:33:07.
 */
class ContainerSetterTest extends \PHPUnit\Framework\TestCase
{
    use ContainerSetter;

    /**
     * @covers Caridea\Container\ContainerSetter::setContainer
     */
    public function testSet()
    {
        $container = new EmptyContainer();
        $this->assertNull($this->container);
        $this->setContainer($container);
        $this->assertSame($container, $this->container);
    }
}
