<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2018 LibreWorks contributors
 * @license   Apache-2.0
 */
namespace Caridea\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-18 at 15:18:17.
 */
class PropertiesTest extends \PHPUnit\Framework\TestCase
{
    protected $file;
    
    public function setUp()
    {
        $this->file = tmpfile();
    }
    
    public function tearDown()
    {
        fclose($this->file);
    }
    
    /**
     * @covers \Caridea\Container\Properties::__construct
     * @covers \Caridea\Container\Properties::typeof
     * @covers \Caridea\Container\AbstractContainer::__construct
     * @covers \Caridea\Container\Properties::doGet
     */
    public function testBasic()
    {
        $properties = [
            'config.host' => 'db.example.net',
            'config.port' => 1337,
            'config.user' => 'nobody',
            'config.date' => new \DateTime('2015-05-18'),
            'config.good' => true,
            'config.perc' => 12.345,
            'config.tags' => ['foo', 'bar'],
            'config.file' => $this->file
        ];
        $object = new Properties($properties, null);
        $this->assertTrue($object->contains("config.host"));
        $this->assertTrue($object->containsType("DateTime"));
        $this->assertSame($properties['config.date'], $object->get('config.date'));
        $this->assertEquals(['config.host' => $properties['config.host'], 'config.user' => $properties['config.user']], $object->getByType('string'));
    }
}
